source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

def sample_pod
    pod 'iOS-WebP', path: '../'
end

target 'iOS-WebP' do
    sample_pod
end

target 'iOS-WebPTests' do
    sample_pod
end
