# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOS-WebP' do
    pod "iOS-WebP", :path => "../"
end

target 'iOS-WebPTests' do

end

